### ISSUE TITLE
Self hosted not recognized

### ISSUE THREAD

**Issue by sfallows** [Litterfeldt/AGhast#5]
I am running ghost 0.5.10 and the app does not recognize either domain I have running.

**Comment by Litterfeldt** [comment]
Alright, can i get some more info?

**Comment by wethefox** [comment]
Same issue here - have tried with and without http:// also tried http://gitbox.org/ghost - keeps saying there's no such site.

**Comment by sfallows** [comment]
What would you like? hosting info? i am using multiple domains on digital ocean droplet using their app installer

**Comment by Litterfeldt** [comment]
Version of Ghost installation would be helpfull.

**Comment by sfallows** [comment]
as mentioned in my first post 0.5.10

**Comment by Litterfeldt** [comment]
My bad, I meant to say the domain of your installation, so that I can debug it.

**Comment by sfallows** [comment]
Seanfallows.com

**Comment by 8bitjeremy** [comment]
Running onto the same issue. I am hosting on a openshift gear and doing cname redirects to my domain. 

ghost-8bitjeremy.rhcloud.com

www.spudz.org

What exactly should we be entering into the form? Full URL, with http, add ghost/?

**Comment by lifehome** [comment]
Mainly it is because corproxy is down, so the js/index.js has been keep returning false, modify or overriding such condition will do the case.

**Comment by Litterfeldt** [comment]
@lifehome the corproxy seems very unstable.

I have now dedicated ~1 week to create a real app using the ghost api. As the current itteration of the app is broken and also quite bad this felt like a good thing to do. 

Anyone want to be beta-testers?

**Comment by lifehome** [comment]
@Litterfeldt Love to if it is going to be open source, but would do either way.

**Comment by Litterfeldt** [comment]
@lifehome It's going to replace this project. Send me over an email and ill send you an apk.

**Comment by 8bitjeremy** [comment]
I can beta test the new app, I have a Nexus7 running Lollipop

**Comment by Litterfeldt** [comment]
@jeremy sweet send me an email and ill forward the apk.
